rvolosatovs/turtlitto

- .gitignore
Requested by Wessel.
This is the first part of the UI branch
> gitignore: Ignore Vim Swapfiles

- front/package.json
- front/yarn.lock
Will be used in the Batterry and NotificationWindow component
> front: Add Font Awesome dependency

- front/src/Battery/__snapshots__/index.test.js.snap
- front/src/Battery/index.js
- front/src/Battery/index.test.js
Most of the actual work was done by Wessel.
> front: Add Battery

- front/src/Dropdown/__snapshots__/index.test.js.snap
- front/src/Dropdown/index.js
- front/src/Dropdown/index.test.js
This is a cherry-pick of 2385175, 26f054f and a partial cherry-pick of 21069da and 541f4ca
> front: Add Dropdown

- pkg/api/api.go
BallFoundCommunicatied -> BallFoundCommunicated
> src: API spelling error corrected

- .travis.yml
- README.md
See https://docs.travis-ci.com/user/caching/#yarn-cache
> ci: Cache Yarn packages

- front/src/NotificationWindow/__snapshots__/index.test.js.snap
- front/src/NotificationWindow/index.js
- front/src/NotificationWindow/index.test.js
- front/src/NotificationWindow/notificationTypes.js
- front/src/theme.js
Cherry-pick of all the commits of NotificationWindow.js
> front: Add NotificationWindow

- pkg/api/api.go
> api: Fix typos

- front/src/BottomBar/__snapshots__/index.test.js.snap
- front/src/BottomBar/connectionTypes.js
- front/src/BottomBar/index.js
- front/src/BottomBar/index.test.js
The BottomBar is now organised differently and a connection bar has been added.
> front: change BottomBar to implement customer feedback

- front/src/BottomBar/index.test.js
- front/src/RefboxField/__snapshots__/index.test.js.snap
- front/src/RefboxField/index.test.js
- front/src/RefboxSettings/DropBall.js
The following linting errors made it into master. I have no clue why, but I suggest we get them fixed before they break more builds.
> front: Fix linting errors

- front/package.json
- front/src/App.js
- front/src/setupTests.js
- front/yarn.lock
Currently nothing is done with this, other than updating the state. The package.json changes are to ensure websocket proxying works.
> front: Add basic websocket connection

- front/src/Battery/__snapshots__/index.test.js.snap
- front/src/Battery/index.test.js
- front/src/Dropdown/__snapshots__/index.test.js.snap
- front/src/Dropdown/index.test.js
- front/src/NotificationWindow/__snapshots__/index.test.js.snap
- front/src/NotificationWindow/index.test.js
- front/src/RefboxField/RefboxButton.test.js
- front/src/RefboxField/__snapshots__/RefboxButton.test.js.snap
- front/src/RefboxField/__snapshots__/index.test.js.snap
- front/src/RefboxField/index.test.js
- front/src/RefboxSettings/ConfigDropdown.test.js
- front/src/RefboxSettings/DropBall.test.js
- front/src/RefboxSettings/InOutButton.test.js
- front/src/RefboxSettings/__snapshots__/ConfigDropdown.test.js.snap
- front/src/RefboxSettings/__snapshots__/DropBall.test.js.snap
- front/src/RefboxSettings/__snapshots__/InOutButton.test.js.snap
- front/src/RefboxSettings/__snapshots__/index.test.js.snap
- front/src/RefboxSettings/index.test.js
- front/src/Turtle/__snapshots__/index.test.js.snap
- front/src/Turtle/index.test.js
Update the battery tests to use enzyme and change the battery percentages to follow the requirements
> Switch to enzyme from react-renderer in tests

- front/src/Turtle/index.js
This breaks SRRS/TRC state change sending
> front: Fix typo in role names

- front/src/App.js
- front/src/Turtle/index.js
- front/src/Turtle/index.test.js
See the TRC interface specifications:
battery -> batteryvoltage
home -> homegoal
team -> teamcolor
> front: Rename Turtle properties to follow specs

- front/src/Settings/__snapshots__/index.test.js.snap
- front/src/Settings/index.js
- front/src/Settings/index.test.js
- front/src/Turtle/index.js
> front: Rename turtle attributes in PropTypes and Settings too

- front/src/NotificationWindow/__snapshots__/index.test.js.snap
- front/src/NotificationWindow/index.js
NotificationWindow now displays a message.
> front: Fix notificationWindow

- front/src/BottomBar/ConnectionBar/__snapshots__/index.test.js.snap
- front/src/BottomBar/ConnectionBar/index.js
- front/src/BottomBar/ConnectionBar/index.test.js
- front/src/BottomBar/__snapshots__/index.test.js.snap
- front/src/BottomBar/index.js
- front/src/BottomBar/index.test.js
- remove the settings/refbox button when using tablet
- add the spinner when in the `connecting` state (can add some advanced stuff later, should be fine for the demo)
- make `ConnectionBar` as a separate component
> Refactor BottomBar

- front/src/Settings/__snapshots__/index.test.js.snap
- front/src/Settings/index.js
- front/src/Settings/index.test.js
- front/src/Turtle/index.js
- front/src/TurtleList/__snapshots__/index.test.js.snap
- front/src/TurtleList/index.js
- front/src/TurtleList/index.test.js
- Move turtles to a separate component - TurtleList
- Change layout when using tablet
- Structure the Settings tests
> Make the TurtleList component

- front/src/TurtleEnableBar/TurtleEnableButton.js
- front/src/TurtleEnableBar/__snapshots__/index.test.js.snap
- front/src/TurtleEnableBar/index.js
- `TurtleEnableButton`s take all available width
- comply with the tablet ui sketch
> Refactor TurtleEnableBar

- front/src/App.js
- front/src/BottomBar/__snapshots__/index.test.js.snap
- front/src/BottomBar/index.js
- front/src/RefboxField/__snapshots__/index.test.js.snap
- front/src/RefboxField/index.js
- front/src/RefboxSettings/__snapshots__/DropBall.test.js.snap
- front/src/RefboxSettings/__snapshots__/InOutButton.test.js.snap
- front/src/RefboxSettings/index.js
- front/src/Settings/__snapshots__/index.test.js.snap
- front/src/Settings/index.js
- front/src/sendToServer.js
As authentication is not done, it is currently done with a dummy token "dummy".
> front: Add token propagation from App.js

- front/src/App.js
- front/src/AuthenticationScreen/__snapshots__/index.test.js.snap
- front/src/AuthenticationScreen/index.js
- front/src/AuthenticationScreen/index.test.js
> front: Add initial AuthenticationScreen

- front/src/App.js
- front/src/App.test.js
Implementation of automatic reconnect feature.
> front: Implement automatic reconnect

- pkg/trcapi/conn.go
Added error when conn wouldn't receive response from TRC within 5 seconds.
> Add timeout to TRC pings

- front/src/App.js
- front/src/App.test.js
Repro steps:
- Start Webpack dev server
- Start SRRS
- Start TRCD
Observe that the SRRC crashes (because "{}\n" was sent as a message)
> front: Only update turtles when actual turtles are sent

- Gopkg.lock
- cmd/srrs/main.go
- cmd/srrs/main_test.go
- pkg/api/api.go
- pkg/api/apitest/apitest.go
- pkg/api/validate.go
- pkg/api/validate_test.go
- pkg/logcontext/context.go
- pkg/trcapi/conn.go
- pkg/trcapi/conn_test.go
- pkg/trcapi/trctest/trc.go
- pkg/webapi/webapi.go
@HaicoDorenbos please look at this branch for the API changes.
> webapi: Add session support, encapsulate logic

- front/src/App.js
- front/src/AuthenticationScreen/__snapshots__/index.test.js.snap
- front/src/AuthenticationScreen/index.js
- front/src/AuthenticationScreen/index.test.js
> front: Add ConnectionBar AuthenticationScreen

- .codecov.yml
See https://docs.codecov.io/docs/node
> coverage: Enable partial line coverage for javascript

- front/src/TurtleList/__snapshots__/index.test.js.snap
- front/src/TurtleList/index.js
This resets the width of the component, preventing a horizontal scrollbar from popping up
> front: Add grid to turtle list

- Makefile
- pkg/trcapi/conn.go
- pkg/trcapi/token_auth.go
- pkg/trcapi/token_noauth.go
- pkg/webapi/webapi.go
@satanja please confirm it works.
> Add support for auth-less builds

- pkg/trcapi/pool.go
> srrs: Fix typos

- front/src/App.js
Reverts rvolosatovs/turtlitto#118
Backend only accepts it in quotes
> Revert "front: fix quoting session key in auth msg."

- pkg/trcapi/conn.go
- pkg/trcapi/trctest/trc.go
- pkg/webapi/webapi.go
- Added WebSocket ping handling
- Improved logging statements
> Webapi: Make compliant with SRD

- front/src/App.js
- front/src/SupportBar.js
Ugly UserAgent hack, shouldn't exist, but unfortunately must.
> front: Add support bar to some browsers

- front/src/Settings/__snapshots__/index.test.js.snap
- front/src/Turtle/__snapshots__/index.test.js.snap
- front/src/Turtle/index.js
- front/src/TurtleList/__snapshots__/index.test.js.snap
- front/src/TurtleList/index.js
- front/src/__snapshots__/App.test.js.snap
> Make battery section take equal width and center
